In [4]:
import pandas as pd
import numpy as np
from collections import Counter
import glob
import os
import matplotlib.pyplot as plt
import datetime
%matplotlib inline
import networkx as nx
from pyvis.network import Network

In [12]:
df = {}
for file in glob.glob("../data/raw/scenario01/csv/*.csv"):
    tmp_df = pd.read_csv(file)
    file_sep = file.split(os.sep)
    df_name = file_sep[len(file_sep) - 1].split('.')[0]
    df[df_name] = tmp_df

In [13]:
df['encounters'].head()

,Id,START,STOP,PATIENT,ORGANIZATION,PROVIDER,PAYER,ENCOUNTERCLASS,CODE,DESCRIPTION,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,REASONCODE,REASONDESCRIPTION
0,38058d5e-b387-3bf4-7e8e-652963121539,2021-08-11T21:01:16Z,2021-08-11T21:16:16Z,7b3c738d-3f86-58e3-450e-4018521d192f,5b73b984-a934-3cb2-b181-be8a4e7d6c49,74ae6031-4392-398b-b2ba-5661afd90b7d,047f6ec3-6215-35eb-9608-f9dda363a44c,wellness,410620009,Well child visit (procedure),136.8,347.38,0.0,NaN,NaN
1,7ce90b77-dcf4-7ef7-6f2e-222b8f8e53af,2021-09-15T21:01:16Z,2021-09-15T21:16:16Z,7b3c738d-3f86-58e3-450e-4018521d192f,5b73b984-a934-3cb2-b181-be8a4e7d6c49,74ae6031-4392-398b-b2ba-5661afd90b7d,047f6ec3-6215-35eb-9608-f9dda363a44c,wellness,410620009,Well child visit (procedure),136.8,272.80,0.0,NaN,NaN
2,3e712884-0b4b-a72a-691b-d81127ed15f7,2021-11-17T21:01:16Z,2021-11-17T21:16:16Z,7b3c738d-3f86-58e3-450e-4018521d192f,5b73b984-a934-3cb2-b181-be8a4e7d6c49,74ae6031-4392-398b-b2ba-5661afd90b7d,047f6ec3-6215-35eb-9608-f9dda363a44c,wellness,410620009,Well child visit (procedure),136.8,1400.05,0.0,NaN,NaN
3,ea214644-3c0a-a8fc-27de-ce4d61fb6707,2022-01-19T21:01:16Z,2022-01-19T21:16:16Z,7b3c738d-3f86-58e3-450e-4018521d192f,5b73b984-a934-3cb2-b181-be8a4e7d6c49,74ae6031-4392-398b-b2ba-5661afd90b7d,047f6ec3-6215-35eb-9608-f9dda363a44c,wellness,410620009,Well child visit (procedure),136.8,1213.88,0.0,NaN,NaN
4,fc30a3b9-b200-6424-206b-9a6bca68c575,2022-04-20T21:01:16Z,2022-04-20T21:16:16Z,7b3c738d-3f86-58e3-450e-4018521d192f,5b73b984-a934-3cb2-b181-be8a4e7d6c49,74ae6031-4392-398b-b2ba-5661afd90b7d,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,wellness,410620009,Well child visit (procedure),136.8,816.80,0.0,NaN,NaN

In [14]:
df['patients'].head()

,Id,BIRTHDATE,DEATHDATE,SSN,DRIVERS,PASSPORT,PREFIX,FIRST,LAST,SUFFIX,...,BIRTHPLACE,ADDRESS,CITY,STATE,COUNTY,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE
0,7b3c738d-3f86-58e3-450e-4018521d192f,2021-08-11,NaN,999-71-7790,NaN,NaN,NaN,Svetlana462,O'Hara248,NaN,...,Boston Massachusetts US,971 Ullrich Grove Suite 53,Boston,Massachusetts,Suffolk County,2135.0,42.304260,-71.045262,22950.9100,0.0000
1,c40c2c75-13c9-8e4a-047f-573ae1330157,2020-03-03,NaN,999-49-5505,NaN,NaN,NaN,Rosalyn434,Christiansen251,NaN,...,Lawrence Massachusetts US,485 Senger Route Apt 34,Waltham,Massachusetts,Middlesex County,2451.0,42.340439,-71.206815,54769.7275,2624.1225
2,39e76039-522c-61f1-d961-e03dce5f0bb2,1998-11-21,2003-07-17,999-36-5991,NaN,NaN,NaN,Lashawnda573,Daniel959,NaN,...,North Reading Massachusetts US,944 Witting Passage,Everett,Massachusetts,Middlesex County,2149.0,42.412900,-71.009282,139148.2750,932.7450
3,ff981e00-4004-44b4-48ba-0bfa62440bb3,2009-07-29,NaN,999-39-5303,NaN,NaN,NaN,Ulysses632,Rice937,NaN,...,Scituate Massachusetts US,414 Rempel Harbor,Cohasset,Massachusetts,Norfolk County,NaN,42.214770,-70.814553,339359.4700,90.6000
4,648dbf91-4334-a7e2-2cfe-72e88dbd4c15,2000-12-04,NaN,999-77-8366,S99996514,X32384432X,Mr.,Tory770,Harvey63,NaN,...,Boston Massachusetts US,368 Pouros Ramp Apt 46,Haverhill,Massachusetts,Essex County,1832.0,42.779225,-71.055842,543267.4075,2173.6425

In [15]:
df['conditions'].head()

,START,STOP,PATIENT,ENCOUNTER,CODE,DESCRIPTION
0,2021-12-26,2022-01-07,c40c2c75-13c9-8e4a-047f-573ae1330157,862287d1-a2eb-8116-de42-e76de6163260,195662009,Acute viral pharyngitis (disorder)
1,1999-05-12,NaN,39e76039-522c-61f1-d961-e03dce5f0bb2,00681d7e-e9bb-392b-6ccb-209cf46e2ec3,128613002,Seizure disorder
2,1999-05-12,NaN,39e76039-522c-61f1-d961-e03dce5f0bb2,00681d7e-e9bb-392b-6ccb-209cf46e2ec3,703151001,History of single seizure (situation)
3,2003-03-04,2003-03-17,39e76039-522c-61f1-d961-e03dce5f0bb2,7ac71954-b14b-f259-f032-bc07d5f4eaa6,43878008,Streptococcal sore throat (disorder)
4,2003-07-17,NaN,39e76039-522c-61f1-d961-e03dce5f0bb2,705cabcc-6c94-1804-ee22-0e0b944ed62f,262574004,Bullet wound

In [16]:
encounters = df['encounters']
encounters['row_number'] = encounters.sort_values(['START'], ascending=[False]) \
             .groupby(['PATIENT']) \
             .cumcount() + 1
last_encounters = encounters[encounters['row_number'] == 1]

In [17]:
patients = df['patients']
patients

,Id,BIRTHDATE,DEATHDATE,SSN,DRIVERS,PASSPORT,PREFIX,FIRST,LAST,SUFFIX,...,BIRTHPLACE,ADDRESS,CITY,STATE,COUNTY,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE
0,7b3c738d-3f86-58e3-450e-4018521d192f,2021-08-11,NaN,999-71-7790,NaN,NaN,NaN,Svetlana462,O'Hara248,NaN,...,Boston Massachusetts US,971 Ullrich Grove Suite 53,Boston,Massachusetts,Suffolk County,2135.0,42.304260,-71.045262,2.295091e+04,0.0000
1,c40c2c75-13c9-8e4a-047f-573ae1330157,2020-03-03,NaN,999-49-5505,NaN,NaN,NaN,Rosalyn434,Christiansen251,NaN,...,Lawrence Massachusetts US,485 Senger Route Apt 34,Waltham,Massachusetts,Middlesex County,2451.0,42.340439,-71.206815,5.476973e+04,2624.1225
2,39e76039-522c-61f1-d961-e03dce5f0bb2,1998-11-21,2003-07-17,999-36-5991,NaN,NaN,NaN,Lashawnda573,Daniel959,NaN,...,North Reading Massachusetts US,944 Witting Passage,Everett,Massachusetts,Middlesex County,2149.0,42.412900,-71.009282,1.391483e+05,932.7450
3,ff981e00-4004-44b4-48ba-0bfa62440bb3,2009-07-29,NaN,999-39-5303,NaN,NaN,NaN,Ulysses632,Rice937,NaN,...,Scituate Massachusetts US,414 Rempel Harbor,Cohasset,Massachusetts,Norfolk County,NaN,42.214770,-70.814553,3.393595e+05,90.6000
4,648dbf91-4334-a7e2-2cfe-72e88dbd4c15,2000-12-04,NaN,999-77-8366,S99996514,X32384432X,Mr.,Tory770,Harvey63,NaN,...,Boston Massachusetts US,368 Pouros Ramp Apt 46,Haverhill,Massachusetts,Essex County,1832.0,42.779225,-71.055842,5.432674e+05,2173.6425
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1169,c815ffa4-2917-2c09-1569-e90d5a89eeb2,1933-05-23,1948-05-19,999-84-8049,NaN,NaN,NaN,Olen518,Hammes673,NaN,...,Arlington Massachusetts US,541 Lakin Promenade,Northampton,Massachusetts,Hampshire County,1053.0,42.284637,-72.589066,4.060467e+04,7632.8415
1170,b7fda58e-8eb1-a2d0-8fbf-57afefce34c6,1933-05-23,2003-12-13,999-57-9348,S99975005,X56712306X,Mr.,Edward499,Cole117,NaN,...,Montague Massachusetts US,498 Shields Trafficway,Northampton,Massachusetts,Hampshire County,NaN,42.354777,-72.593976,1.164761e+06,163012.4570
1171,1b46a593-3b14-53dd-1d2b-b59866e09a18,1933-05-23,2021-08-23,999-98-9276,S99942794,X86239063X,Mr.,Antoine384,Brekke496,NaN,...,Andover Massachusetts US,1093 McClure Village Apt 71,Northampton,Massachusetts,Hampshire County,1062.0,42.405194,-72.755758,5.698680e+05,151240.1710
1172,5eeeb1e8-73c4-f7fa-cbb6-be359624f38e,1933-05-23,1975-02-25,999-47-8049,S99934661,X24881672X,Mr.,Britt177,Breitenberg711,NaN,...,Hopkinton Massachusetts US,572 Sipes Ramp Apt 94,Northampton,Massachusetts,Hampshire County,1053.0,42.288684,-72.671682,1.087981e+05,128412.6970
1173,87770b59-ee92-450f-57fb-53fc8a07a0ef,1933-05-23,NaN,999-22-7793,S99972924,X22865231X,Mr.,Lloyd546,Stehr398,NaN,...,Maynard Massachusetts US,968 Roberts Bypass,Northampton,Massachusetts,Hampshire County,1063.0,42.360350,-72.590618,3.252791e+05,138746.5215

In [18]:
patients_last_encounter = patients.merge(last_encounters, left_on='Id', \
                                         right_on='PATIENT', suffixes=('_patient', '_encounter'))

In [19]:
patients_last_encounter['death_threshold'] = pd.to_datetime(patients_last_encounter['DEATHDATE']).dt.tz_localize(None) - \
pd.to_datetime(patients_last_encounter['START']).dt.tz_localize(None) <= datetime.timedelta(days=7)

In [20]:
patients_last_encounter

,Id_patient,BIRTHDATE,DEATHDATE,SSN,DRIVERS,PASSPORT,PREFIX,FIRST,LAST,SUFFIX,...,ENCOUNTERCLASS,CODE,DESCRIPTION,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,REASONCODE,REASONDESCRIPTION,row_number,death_threshold
0,7b3c738d-3f86-58e3-450e-4018521d192f,2021-08-11,NaN,999-71-7790,NaN,NaN,NaN,Svetlana462,O'Hara248,NaN,...,wellness,410620009,Well child visit (procedure),136.80,816.80,0.0,NaN,NaN,1,False
1,c40c2c75-13c9-8e4a-047f-573ae1330157,2020-03-03,NaN,999-49-5505,NaN,NaN,NaN,Rosalyn434,Christiansen251,NaN,...,wellness,410620009,Well child visit (procedure),136.80,750.16,0.0,NaN,NaN,1,False
2,39e76039-522c-61f1-d961-e03dce5f0bb2,1998-11-21,2003-07-17,999-36-5991,NaN,NaN,NaN,Lashawnda573,Daniel959,NaN,...,wellness,308646001,Death Certification,136.80,0.00,0.0,262574004.0,Bullet wound,1,True
3,ff981e00-4004-44b4-48ba-0bfa62440bb3,2009-07-29,NaN,999-39-5303,NaN,NaN,NaN,Ulysses632,Rice937,NaN,...,ambulatory,185347001,Encounter for problem,85.55,948.35,0.0,162864005.0,Body mass index 30+ - obesity (finding),1,False
4,648dbf91-4334-a7e2-2cfe-72e88dbd4c15,2000-12-04,NaN,999-77-8366,S99996514,X32384432X,Mr.,Tory770,Harvey63,NaN,...,wellness,162673000,General examination of patient (procedure),136.80,1742.22,0.0,NaN,NaN,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1169,c815ffa4-2917-2c09-1569-e90d5a89eeb2,1933-05-23,1948-05-19,999-84-8049,NaN,NaN,NaN,Olen518,Hammes673,NaN,...,wellness,308646001,Death Certification,136.80,0.00,0.0,91861009.0,Acute myeloid leukemia disease (disorder),1,True
1170,b7fda58e-8eb1-a2d0-8fbf-57afefce34c6,1933-05-23,2003-12-13,999-57-9348,S99975005,X56712306X,Mr.,Edward499,Cole117,NaN,...,wellness,308646001,Death Certification,136.80,0.00,0.0,254637007.0,Non-small cell lung cancer (disorder),1,True
1171,1b46a593-3b14-53dd-1d2b-b59866e09a18,1933-05-23,2021-08-23,999-98-9276,S99942794,X86239063X,Mr.,Antoine384,Brekke496,NaN,...,wellness,308646001,Death Certification,136.80,0.00,0.0,840539006.0,COVID-19,1,True
1172,5eeeb1e8-73c4-f7fa-cbb6-be359624f38e,1933-05-23,1975-02-25,999-47-8049,S99934661,X24881672X,Mr.,Britt177,Breitenberg711,NaN,...,wellness,308646001,Death Certification,136.80,0.00,0.0,22298006.0,Myocardial Infarction,1,True
1173,87770b59-ee92-450f-57fb-53fc8a07a0ef,1933-05-23,NaN,999-22-7793,S99972924,X22865231X,Mr.,Lloyd546,Stehr398,NaN,...,urgentcare,702927004,Urgent care clinic (procedure),142.58,142.58,0.0,NaN,NaN,1,False

In [21]:
patients_encouterclasses = encounters.groupby(['PATIENT', 'ENCOUNTERCLASS']).size().unstack('ENCOUNTERCLASS', fill_value=0).reset_index()

In [22]:
patients_encouterclasses

ENCOUNTERCLASS,PATIENT,ambulatory,emergency,home,hospice,inpatient,outpatient,snf,urgentcare,virtual,wellness
0,0000c650-47ba-eaf7-c2e6-ee06774a3d95,2,0,0,0,0,3,0,0,0,9
1,009c30e1-5fa4-f50c-dfa5-bf3092116bbb,6,1,0,0,1,29,0,0,0,10
2,00c2e638-e098-f9ff-3610-5af6f565616d,2,0,0,0,0,5,0,1,0,10
3,00fe47e4-40df-207e-e357-789d2aca44c1,13,0,0,0,0,3,0,0,0,22
4,014e204c-bd87-a7fd-0ee5-86296391a44d,59,4,0,0,1,7,4,0,0,83
...,...,...,...,...,...,...,...,...,...,...,...
1169,fdaa221b-c4ee-7609-2cfc-1f034b15b3ef,16,1,0,0,0,6,0,0,0,9
1170,fe0b3504-c5df-4691-055d-34ad7002a5d1,20,3,0,0,4,45,0,0,0,14
1171,ff34b909-0ce6-1d5e-6b6d-9b96c75f08bb,29,2,0,0,0,9,0,8,0,47
1172,ff981e00-4004-44b4-48ba-0bfa62440bb3,27,0,0,0,0,3,0,0,9,11
1173,ffb18140-91de-27cf-d030-e5e05b6ab528,9,4,0,0,0,4,1,2,0,25

In [23]:
patients_last_encounter = patients_last_encounter.merge(patients_encouterclasses, left_on='Id_patient', \
                              right_on='PATIENT', suffixes=('_patient', '_encounter_classes'))

In [24]:
patients_last_encounter.columns

Index(['Id_patient', 'BIRTHDATE', 'DEATHDATE', 'SSN', 'DRIVERS', 'PASSPORT',
       'PREFIX', 'FIRST', 'LAST', 'SUFFIX', 'MAIDEN', 'MARITAL', 'RACE',
       'ETHNICITY', 'GENDER', 'BIRTHPLACE', 'ADDRESS', 'CITY', 'STATE',
       'COUNTY', 'ZIP', 'LAT', 'LON', 'HEALTHCARE_EXPENSES',
       'HEALTHCARE_COVERAGE', 'Id_encounter', 'START', 'STOP',
       'PATIENT_patient', 'ORGANIZATION', 'PROVIDER', 'PAYER',
       'ENCOUNTERCLASS', 'CODE', 'DESCRIPTION', 'BASE_ENCOUNTER_COST',
       'TOTAL_CLAIM_COST', 'PAYER_COVERAGE', 'REASONCODE', 'REASONDESCRIPTION',
       'row_number', 'death_threshold', 'PATIENT_encounter_classes',
       'ambulatory', 'emergency', 'home', 'hospice', 'inpatient', 'outpatient',
       'snf', 'urgentcare', 'virtual', 'wellness'],
      dtype='object')

In [25]:
conditions = df['conditions']

In [26]:
conditions['row_number'] = conditions.sort_values(['STOP', 'START'], ascending=[False, False]) \
             .groupby(['PATIENT']) \
             .cumcount() + 1

In [27]:
last_conditions = conditions[conditions['row_number'] == 1]

In [28]:
len(list(set(last_conditions['PATIENT'])))

1140

In [29]:
last_conditions

,START,STOP,PATIENT,ENCOUNTER,CODE,DESCRIPTION,row_number
0,2021-12-26,2022-01-07,c40c2c75-13c9-8e4a-047f-573ae1330157,862287d1-a2eb-8116-de42-e76de6163260,195662009,Acute viral pharyngitis (disorder),1
3,2003-03-04,2003-03-17,39e76039-522c-61f1-d961-e03dce5f0bb2,7ac71954-b14b-f259-f032-bc07d5f4eaa6,43878008,Streptococcal sore throat (disorder),1
7,2015-07-01,2015-07-26,ff981e00-4004-44b4-48ba-0bfa62440bb3,d8ccf960-04c3-3876-daa8-d1470a7545aa,444814009,Viral sinusitis (disorder),1
25,2021-02-08,2022-02-14,648dbf91-4334-a7e2-2cfe-72e88dbd4c15,87faf129-174f-f8ba-c351-eb31da8d29c9,160903007,Full-time employment (finding),1
47,2020-06-16,2021-06-22,06a0234c-08a4-b77f-a6db-8b557fbe8510,f3395851-f164-46d2-6113-007dbc45c87f,160904001,Part-time employment (finding),1
...,...,...,...,...,...,...,...
36263,1947-06-01,1947-06-13,c815ffa4-2917-2c09-1569-e90d5a89eeb2,3074a60d-7ca6-6815-888f-42b8cce8e890,444814009,Viral sinusitis (disorder),1
36283,1995-08-01,2003-09-16,b7fda58e-8eb1-a2d0-8fbf-57afefce34c6,051bc787-cf22-09b9-bc4e-3a6f86c877b6,422650009,Social isolation (finding),1
36329,2021-08-09,2021-08-09,1b46a593-3b14-53dd-1d2b-b59866e09a18,4cb14998-5d68-bede-6243-f5305fbdac7c,840544004,Suspected COVID-19,1
36358,1968-10-22,1973-11-20,5eeeb1e8-73c4-f7fa-cbb6-be359624f38e,57159a22-26e2-213b-d659-f20d9d57d5d7,423315002,Limited social contact (finding),1
36395,2022-03-02,2022-03-14,87770b59-ee92-450f-57fb-53fc8a07a0ef,5741ca05-0507-9d45-9fe0-85ee82689ab6,444814009,Viral sinusitis (disorder),1

In [30]:
patient_last_conditions = last_conditions.groupby(['PATIENT', 'CODE']).size(). \
unstack('CODE', fill_value=0).reset_index()

In [31]:
patient_last_conditions

CODE,PATIENT,10509002,16114001,24079001,30832001,32911000,33737001,36971009,38822007,39848009,...,403190006,422650009,423315002,444814009,706870000,706893006,713197008,741062008,840539006,840544004
0,0000c650-47ba-eaf7-c2e6-ee06774a3d95,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,009c30e1-5fa4-f50c-dfa5-bf3092116bbb,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,00c2e638-e098-f9ff-3610-5af6f565616d,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
3,00fe47e4-40df-207e-e357-789d2aca44c1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,014e204c-bd87-a7fd-0ee5-86296391a44d,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1135,fdaa221b-c4ee-7609-2cfc-1f034b15b3ef,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1136,fe0b3504-c5df-4691-055d-34ad7002a5d1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1137,ff34b909-0ce6-1d5e-6b6d-9b96c75f08bb,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1138,ff981e00-4004-44b4-48ba-0bfa62440bb3,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1139,ffb18140-91de-27cf-d030-e5e05b6ab528,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [32]:
patients_last_encounter_conditions = patients_last_encounter.merge(patient_last_conditions, left_on='Id_patient', \
                              right_on='PATIENT', suffixes=('_patient_encounter_classes', '_conditions'))

In [33]:
patients_last_encounter_conditions.columns

Index(['Id_patient',  'BIRTHDATE',  'DEATHDATE',        'SSN',    'DRIVERS',
         'PASSPORT',     'PREFIX',      'FIRST',       'LAST',     'SUFFIX',
       ...
          403190006,    422650009,    423315002,    444814009,    706870000,
          706893006,    713197008,    741062008,    840539006,    840544004],
      dtype='object', length=109)

In [34]:
def get_days_alive(row):
    try:
        return pd.Timedelta(
            pd.to_datetime(
                row['DEATHDATE'], errors='coerce'
            ).tz_localize(None) - \
            pd.to_datetime(
                row['BIRTHDATE'], errors='coerce'
            ).tz_localize(None)
        ).days
    except:
        return pd.NaN

In [35]:
patients_last_encounter_conditions['days_alive'] = patients_last_encounter_conditions.apply(get_days_alive, axis=1)

In [36]:
# TODO: RACE, GENDER e ETHNICITY -> dummyzar

In [37]:
[print(x) for x in patients_last_encounter_conditions.columns]

Id_patient
BIRTHDATE
DEATHDATE
SSN
DRIVERS
PASSPORT
PREFIX
FIRST
LAST
SUFFIX
MAIDEN
MARITAL
RACE
ETHNICITY
GENDER
BIRTHPLACE
ADDRESS
CITY
STATE
COUNTY
ZIP
LAT
LON
HEALTHCARE_EXPENSES
HEALTHCARE_COVERAGE
Id_encounter
START
STOP
PATIENT_patient
ORGANIZATION
PROVIDER
PAYER
ENCOUNTERCLASS
CODE
DESCRIPTION
BASE_ENCOUNTER_COST
TOTAL_CLAIM_COST
PAYER_COVERAGE
REASONCODE
REASONDESCRIPTION
row_number
death_threshold
PATIENT_encounter_classes
ambulatory
emergency
home
hospice
inpatient
outpatient
snf
urgentcare
virtual
wellness
PATIENT
10509002
16114001
24079001
30832001
32911000
33737001
36971009
38822007
39848009
40055000
40275004
43878008
44465007
49727002
58150001
62106007
65363002
65966004
68496003
70704007
72892002
73595000
75498004
80583007
91861009
160701002
160903007
160904001
160968000
192127007
195662009
198992004
232353008
233678006
241929008
248595008
263102004
267036007
283371005
283385000
284549007
284551006
359817006
370247008
386661006
403190006
422650009
423315002
444814009
706870000
706893006
713197008
741062008
840539006
840544004
days_alive

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]